package com.compiler.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Actors generated by hbm2java
 */
@Entity
@Table(name = "Compilations")
public class Compilation implements Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String encryptedCCode;
	private String fileName;
	private int userId;
	private int isNewCompilation;
	private Date createDate;

	@Id
	@Column(name = "Id")
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Encrypted_C_Code")
	public String getEncryptedCCode() {
		return encryptedCCode;
	}

	public void setEncryptedCCode(String encryptedCCode) {
		this.encryptedCCode = encryptedCCode;
	}

	@Column(name = "File_Name")
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "User_Id")
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "Is_New_Compilation")
	public int getIsNewCompilation() {
		return isNewCompilation;
	}

	public void setIsNewCompilation(int isNewCompilation) {
		this.isNewCompilation = isNewCompilation;
	}

	@Column(name = "Create_Date")
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
